# Generated by Django 5.2.5 on 2025-08-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_subjecttag_education_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjecttag",
            name="department",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
