# Generated by Django 5.2.5 on 2025-09-17 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_userprofile_is_student_leader"),
    ]

    operations = [
        migrations.AddField(
            model_name="studysession",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studysession",
            name="parent_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_instances",
                to="core.studysession",
            ),
        ),
        migrations.AddField(
            model_name="studysession",
            name="recurrence_end_date",
            field=models.DateTimeField(
                blank=True, help_text="When to stop recurring", null=True
            ),
        ),
        migrations.AddField(
            model_name="studysession",
            name="recurrence_interval",
            field=models.PositiveIntegerField(
                default=1, help_text="Repeat every X days/weeks/months"
            ),
        ),
        migrations.AddField(
            model_name="studysession",
            name="recurrence_type",
            field=models.CharField(
                choices=[
                    ("none", "No Recurrence"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
