# Generated by Django 5.2.5 on 2025-08-27 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_studynote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subjecttag",
            name="education_level",
            field=models.CharField(
                choices=[
                    ("bachelors", "Bachelors"),
                    ("masters", "Masters"),
                    ("phd", "PhD"),
                ],
                default="bachelors",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjecttag",
            unique_together={("name", "education_level")},
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("bachelors", "Bachelors"),
                            ("masters", "Masters"),
                            ("phd", "PhD"),
                        ],
                        default="bachelors",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
