# Generated by Django 5.2.5 on 2025-09-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_subjecttag_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_student_leader",
            field=models.BooleanField(default=False),
        ),
    ]
